// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdsZk49eDRH6IiSyaqc44VSFUBB3EXbs',
    appId: '1:911524271284:android:3f0b5a1737dd7fa18073e1',
    messagingSenderId: '911524271284',
    projectId: 'amu-roboclub',
    databaseURL: 'https://amu-roboclub.firebaseio.com',
    storageBucket: 'amu-roboclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBosNIwgS7B2_zo-z_V5fGoXMR5lVVIVAI',
    appId: '1:911524271284:ios:f00153000a48f31f8073e1',
    messagingSenderId: '911524271284',
    projectId: 'amu-roboclub',
    databaseURL: 'https://amu-roboclub.firebaseio.com',
    storageBucket: 'amu-roboclub.appspot.com',
    androidClientId: '911524271284-019e7rt0oanpvnq3ej0co91osstrarql.apps.googleusercontent.com',
    iosClientId: '911524271284-2j5jtfarm9sarfqkohn4hpfsottm6ki6.apps.googleusercontent.com',
    iosBundleId: 'com.example.robo',
  );

}